spring:
  application:
    name: producto-service
  datasource:
    url: jdbc:postgresql://localhost:5432/productos_db
    username: postgres
    password: Lopez2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Lopez2003}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true
